# Generated by Django 4.0.4 on 2022-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_rename_drinks_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
