# Generated by Django 4.0.4 on 2022-05-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_alter_drink_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
